name: Handle release process

on:
  push:
    branches: ['release/*']

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ inputs.target_branch || github.head_ref || github.ref_name }}
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          fetch-depth: 500
      - name: Get tags
        run: git fetch --tags origin
      - name: Skip release if there are no new commits since last tag
        run: echo IS_COMMIT_TAGGED=$(git tag --contains HEAD | grep -q . && echo true || echo false) >> $GITHUB_ENV
      - name: Establish release version
        if: env.IS_COMMIT_TAGGED == 'false'
        run: echo "RELEASE_VERSION=${BRANCH_NAME##*/}" >> $GITHUB_ENV
      - name: Establish last release version
        if: env.IS_COMMIT_TAGGED == 'false'
        run: |
          LAST_RELEASE_MAJOR=$([[ $RELEASE_VERSION == *\.0 ]] && echo "[0-9]+" || echo $RELEASE_VERSION | cut -d. -f1 )
          LAST_RELEASE_MINOR=$([[ $RELEASE_VERSION == *\.0 ]] && echo "[0-9]+" || echo $RELEASE_VERSION | cut -d. -f2 )
          LAST_RELEASE_PATCH=$([[ $RELEASE_VERSION == *\.0 ]] && echo "0" || echo "[0-9]+" )
          LAST_RELEASE_REGEX=$LAST_RELEASE_MAJOR\.$LAST_RELEASE_MINOR\.$LAST_RELEASE_PATCH
          LAST_RELEASE_COMMIT=$(git log --grep="chore\(release\/$LAST_RELEASE_REGEX" --extended-regexp --format="%H" -1)
          echo "LAST_RELEASE_COMMIT=$LAST_RELEASE_COMMIT" >> $GITHUB_ENV
      - uses: google-github-actions/release-please-action@v3.7.10
        if: env.IS_COMMIT_TAGGED == 'false'
        id: release-please
        with:
          release-type: node
          package-name: release-please-action
          release-as: ${{ env.RELEASE_VERSION }}
          default-branch: ${{ env.BRANCH_NAME }}
          last-release-sha: cbf719c65a1af9650998135c7f9e5a322179394e
          release-search-depth: 500
          commit-search-depth: 500
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          include-v-in-tag: false

  merge_release-main:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    steps: 
      - name: merge release to main branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
